CREATE TABLE `matches` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NAME` varchar(255) NOT NULL,
  `TYPE` varchar(32) NOT NULL,
  `BEGINTIME` date NOT NULL,
  `ENDTIME` date NOT NULL,
  `COURTID` int(11) DEFAULT NULL,
  `RULE` text,
  `RELTIME` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `VERIFY` char(1) NOT NULL DEFAULT '0',
  `SCORE` text,
  `USERID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `USERID` (`USERID`),
  KEY `COURTID` (`COURTID`),
  CONSTRAINT `matches_ibfk_1` FOREIGN KEY (`USERID`) REFERENCES `user` (`ID`) ON
 DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `matches_ibfk_2` FOREIGN KEY (`COURTID`) REFERENCES `court` (`ID`)
ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=41 DEFAULT CHARSET=utf8
