set foreign_key_checks=0;
create database if not exists SOUSAI DEFAULT CHARSET=UTF8;
use SOUSAI;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/COURTTYPE.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/COURTPIC.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/USERPIC.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/COURT.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/USER.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/IP.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/COLLECTION.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/MATCHES.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/MESSAGE.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/USERMARK.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/REGION.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/MATCHTYPE.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/MATCHCLASS.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/InsertMATCHCLASS.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/InsertCOURT.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/InsertMATCHTYPE.sql;
source G:/Users/myic/workspace/GitProject/sousai/sousai/sqlFolder/sousai1.1/HOTWORD.sql;

-- source /home/myic/git/sousai/sqlFolder/sousai1.1/COURTTYPE.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/COURTPIC.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/USERPIC.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/COURT.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/USER.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/IP.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/COLLECTION.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/MATCHES.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/MESSAGE.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/USERMARK.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/REGION.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/MATCHTYPE.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/MATCHCLASS.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/InsertMATCHCLASS.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/InsertCOURT.sql;
-- source /home/myic/git/sousai/sqlFolder/sousai1.1/InsertMATCHTYPE.sql;

-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/COURTTYPE.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/COURTPIC.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/USERPIC.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/COURT.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/HOTWORD.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/USER.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/IP.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/COLLECTION.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/MATCHES.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/MESSAGE.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/USERMARK.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/REGION.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/MATCHTYPE.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/MATCHCLASS.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/InsertMATCHCLASS.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/InsertCOURT.sql;
-- source C:/users/KING/git/sousai/sqlFolder/sousai1.1/InsertMATCHTYPE.sql;

set foreign_key_checks=1;