set foreign_key_checks=0;
create database if not exists sousai;
use sousai;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/CourtType.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/CourtPic.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/UserPic.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/Court.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/User.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/Ip.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/Collection.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/Matches.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/Message.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/UserMark.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/Region.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/MatchType.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/MatchClass.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/InsertMatchClass.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/InsertCourt.sql;
source G:/Users/myic/workspace/Git/sousai/sqlFolder/sousai1.1/InsertMatchType.sql;

source /home/myic/git/sousai/sqlFolder/sousai1.1/CourtType.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/CourtPic.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/UserPic.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/Court.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/User.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/Ip.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/Collection.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/Matches.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/Message.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/UserMark.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/Region.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/MatchType.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/MatchClass.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/InsertMatchClass.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/InsertCourt.sql;
source /home/myic/git/sousai/sqlFolder/sousai1.1/InsertMatchType.sql;

set foreign_key_checks=1;